config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'admin/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'annonces/index'
  get 'annonces/show'
  get 'annonces/new', as: 'new_annonce'
  get 'annonces/edit'
  get 'annonces/create'
  get 'annonces/update'
  get 'annonces/destroy'
  devise_for :users
  root to: "home#home"
  resources :annonces
  resources :contact, only: [:new, :create]
 
  get '/admin', to: 'admin#index', as: 'admin'
  get '/admin/annonces', to: 'admin#show', as: 'admin_show'




  get '/show/:id', to: 'home#show', as: 'home'
  #  get '/login', to: 'login#login'
  #  post '/signup', to: 'users#new'
  #  post '/signup', to: 'users#create'


end
# new_annonce_path

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/annonce.rb
class Annonce < ApplicationRecord

    belongs_to :ville
  belongs_to :user
  belongs_to :category
  has_many_attached :images

  enum transaction_type: [:vente, :location]
  serialize :additional_properties, JSON
  validates :title, :description, :price, presence: true
  validate :validate_images

  MAX_IMAGES = 5
  MAX_IMAGE_SIZE = 10.megabytes

  def validate_images
    if images.attached?
      if images.length > MAX_IMAGES
        errors.add(:images, "can't be more than #{MAX_IMAGES}")
      end

      images.each do |image|
        if image.blob.byte_size > MAX_IMAGE_SIZE
          errors.add(:images, "must be less than #{MAX_IMAGE_SIZE / 1.megabyte}MB")
        end
      end
    else
      errors.add(:images, "can't be blank")
    end
  end
end

app/models/annonce_info.rb
class AnnonceInfo < ApplicationRecord
    paginates_per 10

    
    before_save :set_created_at

  
    private
    
    def set_created_at
      self.created_at ||= Time.now
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :annonces
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :message, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



has_many :annonces
belongs_to :ville


validates :phone_number, format: { with: /\A0\d{9}\z/, message: "must start with 0 and have a total length of 10" }
end

app/models/ville.rb
class Ville < ApplicationRecord

    has_many :annonces
    has_many :users
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController


  def index
    @annonces = AnnonceInfo.all
  end
  def show
    @annonces = Annonce.all

  end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    rescue_from ActiveRecord::RecordNotFound, with: :render_404
    rescue_from ActionController::RoutingError, with: :render_404

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number, :ville_id])
      devise_parameter_sanitizer.permit(:account_update, keys: [:phone_number, :ville_id])
    end

    private

    def render_404
      respond_to do |format|
        format.html { render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found }
        format.all { render plain: "404 Not Found", status: :not_found }
    end
    
    end
end

app/controllers/concerns/annonces_controller.rb
class AnnoncesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_annonce, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]

  def new
    @annonce = Annonce.new
  end

  def create
    @annonce = current_user.annonces.build(annonce_params)
    if @annonce.save
      redirect_to annonces_index_path, notice: 'L\'annonce a été créée avec succès.'
    else
      render :new
    end
  end
  def index
    @annonces = current_user.annonces.order(created_at: :desc)
    @annonces = current_user.where(category_id: params[:category_id]) if params[:category_id].present?
    @annonces = current_user.where(ville_id: params[:ville_id]) if params[:ville_id].present?
  end
  def edit
  end

  def update
    if @annonce.update(annonce_params)
      redirect_to annonces_index_path, notice: 'L\'annonce a été mise à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @annonce.destroy
    redirect_to annonces_url, notice: 'Annonce a été détruite avec succès.'
  end

  private

  def set_annonce
    @annonce = Annonce.find(params[:id])
  end

  def check_owner
    if @annonce.user != current_user
      redirect_to @annonce, alert: "Vous n'êtes pas autorisé à effectuer cette action."
    end
  end

  def annonce_params
    params.require(:annonce).permit(:title, :description, :price, :etat, :type_transaction, :ville_id, :category_id, images: [])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def new
      @contact = Contact.new
    end
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
          flash[:success] = "Thank you We will be in touch soon."
          redirect_to root_path
        else
          flash[:error] = "Oops! Something went wrong. Please try again."
          render :new
        end
    end
    
      private
    
      def contact_params
        params.require(:contact).permit(:name, :email, :boutique_name, :country, :message)
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    
      
    def home
        if params[:keyword].present?
            @annonces = AnnonceInfo.where('title LIKE ?', "%#{params[:keyword]}%").page(params[:page])
          else
            @annonces = AnnonceInfo.all.page(params[:page])
          end
    end
    
    def show
        @annonce = AnnonceInfo.find(params[:id])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/annonces/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Annonces#create</h1>
  <p>Find me in app/views/annonces/create.html.erb</p>
</div>

app/views/annonces/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Annonces#destroy</h1>
  <p>Find me in app/views/annonces/destroy.html.erb</p>
</div>

app/views/annonces/index.html.erb
<style>
#btn{

      position: relative;
    bottom: 182px;
    left: 312px; 
}
</style>
<% if flash[:notice] %>
 
  <div class="text-white px-6 py-4 border-0 rounded relative mb-4 bg-emerald-500 flex m-8 ">
  <span class="text-xl inline-block mr-5 align-middle">
    <i class="fas fa-bell" />
  </span>
  <span class="inline-block align-middle mr-8">
    <b class="capitalize">Sucess!</b> T<%= flash[:notice] %>
  </span>
  <button class="absolute bg-transparent text-2xl font-semibold leading-none right-0 top-0 mt-4 mr-6 outline-none focus:outline-none">
    <span>×</span>
  </button>
</div>
<% end %>


<div class="p-10 grid grid-cols-3 gap-5">

<% @annonces.each do |annonce| %>


<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-1 gap-5">
    <!--Card 1-->
  
    <div class="rounded overflow-hidden shadow-lg">
       <a href="<%= annonce_path(annonce) %>">
        <% if annonce.images.attached? %>
             <%= image_tag url_for(annonce.images.first.variant(resize_to_limit: [300, 300])), class: "w-full h-400" %>
      <% end %>
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2"><%=annonce.title%>   <%= link_to "Update", edit_annonce_path(annonce), class: "bg-yellow-500 text-white active:bg-yellow-600 font-bold uppercase text-xs px-2 py-2 rounded-full shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" %>
       
      </div>
        <p class="text-gray-700 text-base">
          <%=annonce.description%> 
        </p>
      </div>
      </a>
      <div class="px-6 pt-4 pb-2">
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#<%=annonce.price%>Dh</span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#<%=annonce.ville.name%></span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">##<%=annonce.etat%></span>
   
      </div>
      <%= button_to annonce_path(annonce), method: :delete, data: { confirm: "Are you sure?" }, id: "btn",class: "bg-red-500 text-white active:bg-red-600 font-bold uppercase text-xs px-2 py-2 rounded-full shadow hover:shadow-md outline-none focus:outline-none mb-1 ease-linear transition-all duration-150" do%>
      
        Delete
      <%end%>
       
    </div>

   

    
   
  </div>

<% end %>

</div>

app/views/annonces/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Annonces#update</h1>
  <p>Find me in app/views/annonces/update.html.erb</p>
</div>

app/views/contact/new.html.erb
      
     

            <div class="bg-gradient-to-b from-purple-600 to-indigo-700 h-96 w-full m-">
    

      
      
        
  <%= form_with(model: @contact, url: contact_index_path, class: 'md:px-20 px-4 py-8') do |form| %>
           
        
     
  
            <div class="md:px-20 px-4 py-8">
                <div class="flex items-center justify-between">
           
                    <div class="lg:hidden text-white">
                        <img id="open" onclick="MenuHandler(true)" src="../svg/svg2.svg" alt="open"/>
                        
                        <div id="close" class="hidden close-m-menu" onclick="MenuHandler(false)">
                            <img src="https://tuk-cdn.s3.amazonaws.com/can-uploader/contact1-svg3.svg" alt="close"/>
                           
                        </div>
                    </div>
                </div>
                                 
                <nav class="lg:hidden relative z-40">
                    <div class="w-full">
                        <div class="visible flex items-center">
                            <ul id="list" class="hidden p-2 bg-white absolute rounded top-0 left-0 right-0 shadow mt-6">
                                <li class="flex cursor-pointer text-gray-600 dark:text-gray-200 text-sm leading-3 tracking-normal mt-2 py-2 hover:text-indigo-700 focus:text-indigo-700 focus:outline-none">
                                    <a href="javascript:void(0)">
                                        <span class="ml-2 font-bold">Home</span>
                                    </a>
                                </li>
                                <li class="flex flex-col cursor-pointer text-gray-600 dark:text-gray-200 text-sm leading-3 tracking-normal py-2 hover:text-indigo-700 focus:text-indigo-700 focus:outline-none flex justify-center" onclick="dropdownHandler(this)">
                                    <a href="javascript:void(0)">
                                        <span class="ml-2 font-bold">About</span>
                                    </a>
                                </li>
                                <li class="flex cursor-pointer text-gray-600 dark:text-gray-200 text-sm leading-3 tracking-normal py-2 hover:text-indigo-700 flex items-center focus:text-indigo-700 focus:outline-none">
                                    <a href="javascript:void(0)">
                                        <span class="ml-2 font-bold">Page</span>
                                    </a>
                                </li>
                                <li class="flex flex-col cursor-pointer text-gray-600 dark:text-gray-200 text-sm leading-3 tracking-normal py-2 hover:text-indigo-700 focus:text-indigo-700 focus:outline-none flex justify-center" onclick="dropdownHandler(this)">
                                    <a href="javascript:void(0)">
                                        <span class="ml-2 font-bold">Doc</span>
                                    </a>
                                </li>
                                <li class="flex flex-col cursor-pointer text-gray-600 dark:text-gray-200 text-sm leading-3 tracking-normal py-2 hover:text-indigo-700 focus:text-indigo-700 focus:outline-none flex justify-center" onclick="dropdownHandler(this)">
                                    <a href="javascript:void(0)">
                                        <span class="ml-2 font-bold">Contact</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
            <div class="w-full flex items-center justify-center my-12">
                <div class="absolute top-40 bg-white dark:bg-gray-800 shadow rounded py-16 lg:px-28 px-8">
           
  
<% if flash[:error] %>

            <!-- Code block starts -->
            <div class="flex items-center justify-center px-4 sm:px-0">
                <div role="alert" id="alert" class="lg:w-10/12 transition duration-150 ease-in-out bg-red-100 shadow rounded-md md:flex justify-between items-center top-0 mt-12 mb-8 py-4 px-4">
                    <div class="sm:flex items-center">
                        <div class="flex items-end">
                            <div class="mr-2 mt-0.5 sm:mt-0 text-red-700">
                               <img class="focus:outline-none" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/color-coded-with-icon-warning-svg1.svg" alt="danger" />
                            </div>
                            <p class="mr-2 text-base font-bold text-red-700">Danger</p>
                        </div>
                        <div class="h-1 w-1 bg-red-700 rounded-full mr-2 hidden xl:block"></div>
                        <p class="text-base text-red-700"><%=flash[:error]%></p>
                    </div>
                    
                </div>
            </div>
            <!-- Code block ends -->
        
<% end %>

                    <p class="md:text-3xl text-xl font-bold leading-7 text-center text-gray-700 dark:text-white">Contact Support</p>
                    <div class="md:flex items-center mt-12">
                        <div class="md:w-72 flex flex-col">
                            <label class="text-base font-semibold leading-none text-gray-800 dark:text-white">Name</label>
                          <%= form.text_field :name, tabindex: "0", aria_label: "Please input name", type: "name", class: "text-base leading-none text-gray-900 p-3 focus:oultine-none focus:border-indigo-700 mt-4 bg-gray-100 border rounded border-gray-200 placeholder-gray-100", placeholder: "Please input name" %>
                        </div>
                        <div class="md:w-72 flex flex-col md:ml-6 md:mt-0 mt-4">
                            <label class="text-base font-semibold leading-none text-gray-800 dark:text-white">Email Address</label>
                           <%= form.email_field :email, tabindex: "0", aria_label: "Please input email address", type: "email", class: "text-base leading-none text-gray-900 p-3 focus:oultine-none focus:border-indigo-700 mt-4 bg-gray-100 border rounded border-gray-200 placeholder-gray-100", placeholder: "Please input email address" %>
                        </div>
                    </div>
                    <div class="md:flex items-center mt-8">
                        <div class="md:w-72 flex flex-col">
                            <label class="text-base font-semibold leading-none text-gray-800 dark:text-white">Company name</label>
                             <%= form.text_field :boutiqueName, tabindex: "0", role: "input", aria_label: "Please input company name", type: "text", class: "text-base leading-none text-gray-900 p-3 focus:outline-none focus:border-indigo-700 mt-4 bg-gray-100 border rounded border-gray-200 placeholder-gray-100", placeholder: "Please input company name" %>

                        </div>
                        <div class="md:w-72 flex flex-col md:ml-6 md:mt-0 mt-4">
                            <label class="text-base font-semibold leading-none text-gray-800 dark:text-white">Country</label>
                           <%= form.text_field :country, tabindex: "0", aria_label: "Please input country name", type: "text", class: "text-base leading-none text-gray-900 p-3 focus:outline-none focus:border-indigo-700 mt-4 bg-gray-100 border rounded border-gray-200 placeholder-gray-100", placeholder: "Please input country name" %>
                        </div>
                    </div>
                    <div>
                        <div class="w-full flex flex-col mt-8">
                            <label class="text-base font-semibold leading-none text-gray-800 dark:text-white">Message</label>
                             <%= form.text_area :message, tabindex: "0", aria_label: "leave a message", role: "textbox", class: "h-36 text-base leading-none text-gray-900 p-3 focus:outline-none focus:border-indigo-700 mt-4 bg-gray-100 border rounded border-gray-200 placeholder-gray-100 resize-none" %>    
                        </div>
                    </div>
                    <p class="text-xs leading-3 text-gray-600 dark:text-gray-200 mt-4">By clicking submit you agree to our terms of service, privacy policy and how we use data as stated</p>
                    <div class="flex items-center justify-center w-full">
                        <%=form.submit "Submit" ,class:"mt-9 text-base font-semibold leading-none text-white py-4 px-10 bg-indigo-700 rounded hover:bg-indigo-600 focus:ring-2 focus:ring-offset-2 focus:ring-indigo-700 focus:outline-none"%>
                    </div>
                </div>
            </div>
        </div>
      <%end%>
        
    <script>
        const MenuHandler = (flag) => {
    if (flag) {
        document.getElementById("list").classList.add("top-100");
        document.getElementById("list").classList.remove("hidden");
        document.getElementById("close").classList.remove("hidden");
        document.getElementById("open").classList.add("hidden");
    } else {
        document.getElementById("list").classList.remove("top-100");
        document.getElementById("list").classList.add("hidden");
        document.getElementById("close").classList.add("hidden");
        document.getElementById("open").classList.remove("hidden");
    }
};


  // Wait for the document to be ready

var Alert = document.getElementById("alert");
var close = document.getElementById("close-modal");
Alert.style.transform = "translateY(0%)";
function closeAlert() {
    Alert.style.transform = "translateY(-200%)";
    setTimeout(function () {
        Alert.style.transform = "translateY(0%)";
    }, 1000);
}
    </script>

   
    
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AvitoClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-mjKWMzA9yabNt61+5tIbWtK8Jw2MS+JN41Mn12B9kW4j4SEv/BkfcdRQ2oL5IlWHPAbZ+wo1dnJGq3OqYEkG0A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>

    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

  
  <%=render 'layouts/shared/nav'%>
     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>